### ISSUE TITLE
Invalid signing due to updated algorithm on Tuya backend as of 1st July 2021

### ISSUE THREAD

**Issue by XeSSiV** [TuyaAPI/cli#128] opened 2021-07-01 15:57 UTC
I've encountered this message in the IoT Platform: To better secure your cloud development, Tuya will upgrade the signature algorithm. Projects created after June 30, 2021 are subject to signature verification with the new algorithm
Link to further documentation is [here: ](https://developer.tuya.com/en/docs/iot/singnature?id=Ka43a5mtx1gsc)

I believe this is causing the wizard, link, and possibly get commands via CLI to fail, though I have no way of confirming this because I do not have a project created that uses the older signing method.

I was able to obtain a local key from a device by installing Smart Life 3.12.6 and downloading the cert via QR code with proxy, and have added the device into Home Assistant, but I'm needing to decipher what the dps for the device are, and it's proving quite difficult without assistance from the CLI features which I am unable to use.

See debug details below

> C:\Users\User>set DEBUG=* & tuya-cli wizard
? The API key from tuya.com: xxxxxxxxxxxx
? The API secret from tuya.com xxxxxxxxxxxxxxx
? Provide a 'virtual ID' of a device currently registered in the app: xxxxxxxxxxxxxx
[
  Error: sign invalid
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\openapi\dist\api.js:74:31)
      at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5),
  Error: sign invalid
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\openapi\dist\api.js:74:31)
      at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5),
  Error: sign invalid
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\openapi\dist\api.js:74:31)
      at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5),
  Error: sign invalid
      at OpenAPI._client.got_1.default.extend.hooks.afterResponse (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\@tuyapi\openapi\dist\api.js:74:31)
      at EventEmitter.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@tuyapi\cli\node_modules\got\dist\source\as-promise.js:87:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
]
There was an issue fetching that device. Make sure your account is linked and the ID is correct.

**Comment by codetheweb** [comment] 2021-07-02 14:35
Duplicate of https://github.com/codetheweb/tuyapi/issues/492, please track there.

**Closed by codetheweb** 2021-07-02 14:35 UTC
