### ISSUE TITLE
scrolling testing text

### ISSUE THREAD

**Issue by akeslo** [TuyaAPI/cli#143] opened 2022-01-09 03:09 UTC
Hi any tuya-cli command just returns a scrolling "testing" string over and over again:

![image](https://user-images.githubusercontent.com/3003773/148667687-f2e71072-20cb-463e-b9a7-fd9a7dab4772.png)

**Comment by elderflow** [comment] 2022-01-09 04:49
I see this, too. I've tried running in a fresh Alpine Linux docker container with the same result.

**Comment by r0swell** [comment] 2022-01-09 12:38
Same results on my freebsd 12 box

**Comment by subhashisbhowmik** [comment] 2022-01-09 13:22
+1

Same in Ubuntu, Ubuntu on RPi, RHEL, Windows, Windows WSL and Mac

**Comment by Blacksli** [comment] 2022-01-09 14:34
+1 
Same
Ubuntu 20

**Comment by subhashisbhowmik** [comment] 2022-01-09 16:55
I was able to circumvent this manually:

1. Install nodejs
2. Download the repo, cd into the directory, run `npm install`
3. Run `node cli.js ...`  (replace ... with your options)

**Comment by akeslo** [comment] 2022-01-09 17:14
> Same in Ubuntu, Ubuntu on RPi, RHEL, Windows, Windows WSL and Mac

Thanks workaround working for me

**Comment by elderflow** [comment] 2022-01-09 17:40
Same here, workaround is OK for me on MacOS and in the Alpine Docker image.

**Comment by codetheweb** [comment] 2022-01-09 18:30
At first I was absolutely sure this was unusually high-effort spam. Then I reproduced the exact same issue in my terminal.

It appears that the maintainer of a popular [terminal library](https://github.com/Marak/colors.js/issues/285) decided to pull a prank on all the 22m installers of his package. It seems like there might be some [other weird stuff](https://nypost.com/2020/09/16/resident-of-nyc-home-with-suspected-bomb-making-materials-charged/amp/) going on with him so I hope he gets better / finds some help for whatever he's going through.

Regardless, this should be fixed in v1.18.3.

**Closed by codetheweb** 2022-01-09 18:30 UTC

**Comment by subhashisbhowmik** [comment] 2022-01-10 11:57
@codetheweb I'm new to node (read: learnt yesterday), do you know why it worked with the workaround I mentioned? How can I reproduce this  after pulling the repo?

**Comment by codetheweb** [comment] 2022-01-11 03:33
To be honest, I'm not really sure why that worked. `colors@1.4.1` is  the broken version, `colors@1.4.0` is a previously working version--so my fix was to change `"colors": "^1.4.0"` in `package.json` (which matched `colors@1.4.1`) to just `"colors": "1.4.0"` (which does not match `colors@1.4.1`).

Not sure why npm module resolution would be slightly different between a globally installed version of `@tuyapi/cli` and a local version.

**Comment by subhashisbhowmik** [comment] 2022-01-11 11:26
> Not sure why npm module resolution would be slightly different between a globally installed version of `@tuyapi/cli` and a local version.

I think I got it, it is because the package-lock file in the repo contains colors@1.4.0, which probably gets ignored during the release. But again, I'm not really familiar with node and npm.
